services:
  rush: &default
    build: .
    image: dannyben/rush

  rush-tagged:
    <<: *default
    image: dannyben/rush:0.7.11

  bash:
    <<: *default
    entrypoint: bash

  version:
    image: dannyben/rush
    command: --version
